using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace XYZUniversityAPI.Domain.Entities
{
    public class Payment
    {
        [Key]
        public int PaymentId { get; set; }

        // Internal system reference (generated by your system)
        [Required]
        [MaxLength(50)]
        public string ReferenceNumber { get; set; } = null!;

        // Bank / payment gateway reference (set after confirmation)
        [MaxLength(100)]
        public string? BankReference { get; set; }

        [Required]
        [ForeignKey(nameof(Student))]
        public string AdmissionNumber { get; set; } = null!;

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; } // payment amount

        [Required]
        [MaxLength(150)]
        public string PaidBy { get; set; } = null!;

        // Payment lifecycle
        [Required]
        public PaymentStatus Status { get; set; }

        // Foreign keys
        [Required]
        public int PaymentTypeId { get; set; }

        [Required]
        public int PaymentChannelId { get; set; }

        // Set ONLY when payment is confirmed
        public DateTime? PaymentDate { get; set; }

        // When payment intent was created
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        // Navigation properties
        public Student Student { get; set; } = null!;
        public PaymentType PaymentType { get; set; } = null!;
        public PaymentChannel PaymentChannel { get; set; } = null!;
    }
}
